dir_dataset: 'datasets/TUM-RGBD'
dir_prediction: 'predictions'
dataset_name: 'tum-rgbd'
scene_names: ['rgbd_dataset_freiburg1_desk', 'rgbd_dataset_freiburg2_xyz', 'rgbd_dataset_freiburg3_long_office_household']
num_evaluation_frames: 125
tracking_module: 'dpvo'
enhancement_module: 'depth'
mapping_module: 'nerfstudio'
multithreading: True
performance_tracking: True
cache_dataset: True
first_frame_index: 0
last_frame_index: -1
frame_stride: 1
num_keyframes: 192
frame_height: 240
frame_width: 320
patches_per_frame: 96
removal_window: 28
optimization_window: 13
patch_lifetime: 15
keyframe_threshold: 15
mapping_iterations: 8192
mapping_snapshot_iterations: 8192